### ISSUE TITLE
puppet apply -e 'include oraclejava' doesn't works 

### ISSUE THREAD

**Issue by c4m4** [neillturner/oraclejava#1]
i'm trying to use your module for install java, but using puppt apply -e 'include oraclejava' doesn't work without using 'Exec { path => [ "/bin/", "/sbin/" , "/usr/bin/", "/usr/sbin/" ] }' with an error like this:

Debug: /File[/usr/java]/selrange: Found selrange default 's0' for /usr/java
Error: Validation of Exec[remove_download_oracle_jdk7] failed: 'rm -f /tmp/jdk-7u67-linux-x64.tar.gz?_' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/oraclejava/manifests/jdk7.pp:30
Wrapped exception:
'rm -f /tmp/jdk-7u67-linux-x64.tar.gz?_' is not qualified and no path was specified. Please qualify the command or specify a path.

I'm using redhat 6.6 puppet server

**Comment by neillturner** [comment]
I suspect it cannot find the rm command because the exec path is not set. some people put the full path names for commands like /bin/rm  instead of rm so this could be a workaround for you. the problem with doing this is that on different unixs this path for commands could be different. 
if you dont have an exec path dont't you get similar problems running other modules?

**Comment by c4m4** [comment]
using the puppetlabs-tomcat module i don't have this problem, because the path attribute is set in every exec resource, thanks anyway :)

**Comment by neillturner** [comment]
i'll have a look at the puppet-tomcat module again as i'm familiar. always interested in improving the modules. i certainly dont know everything about puppet...

**Comment by c4m4** [comment]
I'm learning puppet too, i discovered you can avoid to specify the path of the command for every exec resource, defining the path in your main site.pp as follow "Exec { path => "/usr/bin:/usr/sbin/:/bin:/sbin" }"

**Comment by neillturner** [comment]
yes that's how i do it.
